version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.coolify
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Database Configuration
      - VITE_DB_CLIENT=${VITE_DB_CLIENT:-mysql}
      - VITE_DB_HOST=${VITE_DB_HOST:-localhost}
      - VITE_DB_PORT=${VITE_DB_PORT:-3306}
      - VITE_DB_USER=${VITE_DB_USER:-root}
      - VITE_DB_PASSWORD=${VITE_DB_PASSWORD:-}
      - VITE_DB_NAME=${VITE_DB_NAME:-jboilerplate}
      - VITE_DB_SSL=${VITE_DB_SSL:-false}
      # API Configuration
      - VITE_API_URL=${VITE_API_URL:-}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-30000}
      # Feature Flags
      - VITE_FEATURE_DARK_MODE=${VITE_FEATURE_DARK_MODE:-true}
      - VITE_FEATURE_MULTILINGUAL_SUPPORT=${VITE_FEATURE_MULTILINGUAL_SUPPORT:-true}
      - VITE_FEATURE_NOTIFICATIONS=${VITE_FEATURE_NOTIFICATIONS:-true}
      - VITE_FEATURE_ANALYTICS=${VITE_FEATURE_ANALYTICS:-false}
      - VITE_FEATURE_ADMIN_DASHBOARD=${VITE_FEATURE_ADMIN_DASHBOARD:-true}
      - VITE_FEATURE_USER_MANAGEMENT=${VITE_FEATURE_USER_MANAGEMENT:-true}
      - VITE_FEATURE_EMAIL_SERVICE=${VITE_FEATURE_EMAIL_SERVICE:-false}
    ports:
      - "${WEB_PORT:-3100}:3000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s